/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UsuarioController;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import model.UsuarioModel;

/**
 *
 * @author guilherme
 */
public class UsuarioView extends javax.swing.JFrame {

    private String operacao;
    String colunas[] = {"ID", "Nome", "Ativo", "Cadastro"};
    // esse objeto será vinculado com a tabela
    // selecione o objeto tabela, clique em PROPRIEDADES e encontre MODEL
    // no combo "Definir Propriedades" escolha "Código Personalizado"
    // digite o objeto DefaultTableModel, neste exemplo é dtmUsuario(criado logo abaixo)
    private ArrayList<UsuarioModel> arrayusuario;
    UsuarioTableModel mtb;

    public UsuarioView() {
        initComponents();
        setOperacao(""); // inicializa o form no modo CONSULTA
        setLocationRelativeTo(null);
        setVisible(true);
        consultaUsuario();
        // adiciona evento para que qdo navegar no JTable, atualize o registro nos JTextField´s
        jTableConsulta.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent evt) {
                if (evt.getValueIsAdjusting()) {
                    return;
                }
                int selecionado = jTableConsulta.getSelectedRow();
                if (selecionado >= 0) {
                    mostraUsuario(arrayusuario.get(selecionado));
                }
            }
        });
        pack();
    }

    private String getOperacao() {
        return operacao;
    }

    private void setOperacao(String operacao) {
        Boolean ativar = (operacao.equals("") ? false : true);
        // operacao=""(consulta), operacao="incluir"(inclusão), operacao="alterar"(alteração)
        this.operacao = operacao;
        jBttnGravar.setEnabled(ativar);
        jBttnGravar.setEnabled(ativar);
    }

    private void limparAgenda() {
        jTxtID.setText("0");
        jTxtNome.setText("");
        jTxtCadastro.setText("");
        jCheckAtivo.setSelected(false);
    }

    private void mostraUsuario(UsuarioModel usuario) {
        jTxtID.setText(String.valueOf(usuario.getID()));
        jTxtNome.setText(usuario.getNOME());
        jTxtCadastro.setText(usuario.getCADASTRO());
        jCheckAtivo.setSelected((usuario.getATIVO() == 1));
    }

    private String filtroConsulta() {
        String condicao = "";
        if (!jTxtConsultaID1.getText().trim().equals("")) {
            condicao += "(ID >= " + jTxtConsultaID1.getText() + ")";
        }
        if (!jTxtConsultaID2.getText().trim().equals("")) {
            if (!condicao.isEmpty()) {
                condicao += " AND ";
            }
            condicao += "(ID <= " + jTxtConsultaID2.getText() + ")";
        }
        if (!jTxtConsultaNome.getText().trim().equals("")) {
            if (!condicao.isEmpty()) {
                condicao += " AND ";
            }
            condicao += "(NOME LIKE ('%" + jTxtConsultaNome.getText() + "%'))";
        }
        return condicao;
    }

    private void consultaUsuario() {
        String condicao = filtroConsulta();
        UsuarioController usuariocontroller = new UsuarioController();
        arrayusuario = null;
        arrayusuario = usuariocontroller.consultar(condicao);
        if (arrayusuario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não Existem Usuários Cadastrados !");
        } else {
            mtb = new UsuarioTableModel(arrayusuario, colunas);
            jTableConsulta.setModel(mtb);
            jTableConsulta.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jBttnNovo = new javax.swing.JButton();
        jBttnAlterar = new javax.swing.JButton();
        jBttnExcluir = new javax.swing.JButton();
        jBttnGravar = new javax.swing.JButton();
        jBttnSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtID = new javax.swing.JTextField();
        jTxtNome = new javax.swing.JTextField();
        jTxtCadastro = new javax.swing.JTextField();
        jCheckAtivo = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtConsultaID1 = new javax.swing.JTextField();
        jTxtConsultaNome = new javax.swing.JTextField();
        jTxtConsultaID2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableConsulta = new javax.swing.JTable();
        jBttnConsulta = new javax.swing.JButton();
        jBttnLimpar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jBttnNovo.setText("Novo");
        jBttnNovo.setFocusable(false);
        jBttnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBttnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBttnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(jBttnNovo);

        jBttnAlterar.setText("Alterar");
        jBttnAlterar.setFocusable(false);
        jBttnAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBttnAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBttnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnAlterarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBttnAlterar);

        jBttnExcluir.setText("Excluir");
        jBttnExcluir.setFocusable(false);
        jBttnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBttnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBttnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnExcluirActionPerformed(evt);
            }
        });
        jToolBar1.add(jBttnExcluir);

        jBttnGravar.setText("Gravar");
        jBttnGravar.setFocusable(false);
        jBttnGravar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBttnGravar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBttnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnGravarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBttnGravar);

        jBttnSair.setText("Sair");
        jBttnSair.setFocusable(false);
        jBttnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBttnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBttnSair);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Usuario"));

        jLabel2.setText("ID");

        jLabel3.setText("NOME");

        jLabel4.setText("DATA DE CADASTRO");

        jCheckAtivo.setText("ATIVO?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckAtivo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jCheckAtivo)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Usuarios");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta"));

        jLabel5.setText("ID");

        jLabel6.setText("A");

        jLabel7.setText("NOME");

        jScrollPane2.setViewportView(jTableConsulta);

        jBttnConsulta.setText("CONSULTA");
        jBttnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnConsultaActionPerformed(evt);
            }
        });

        jBttnLimpar.setText("LIMPAR");
        jBttnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTxtConsultaID1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtConsultaID2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBttnConsulta))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTxtConsultaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBttnLimpar))))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBttnConsulta, jBttnLimpar});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jTxtConsultaID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtConsultaID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBttnConsulta))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtConsultaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBttnLimpar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(187, 187, 187))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnAlterarActionPerformed
        setOperacao("alterar");
    }//GEN-LAST:event_jBttnAlterarActionPerformed

    private void jBttnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnNovoActionPerformed
        limparAgenda();
        setOperacao("incluir");
        jTxtNome.setFocusable(true);
        jCheckAtivo.setSelected(true);
    }//GEN-LAST:event_jBttnNovoActionPerformed

    private void jBttnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnExcluirActionPerformed
        setOperacao("");
        if (JOptionPane.showConfirmDialog(null, "Confirma Exclusão deste Usuário ?",
                "Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                UsuarioModel objusuario = new UsuarioModel();
                objusuario.setID(Integer.parseInt(jTxtID.getText()));
                objusuario.setNOME(jTxtNome.getText());
                objusuario.setCADASTRO(jTxtCadastro.getText());
                objusuario.setATIVO((jCheckAtivo.isSelected() ? 1 : 0));

                UsuarioController usuariocontroller = new UsuarioController();
                usuariocontroller.excluir(objusuario);

                JOptionPane.showMessageDialog(null, "Usuário Excluído com Sucesso");
                consultaUsuario();
            } catch (NumberFormatException | HeadlessException ex) {
                JOptionPane.showMessageDialog(null, "Erro na Exclusão do Usuário \n" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jBttnExcluirActionPerformed

    private void jBttnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnGravarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Gravação deste Usuário ?",
                "Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                UsuarioModel objusuario = new UsuarioModel();
                objusuario.setID(Integer.parseInt(jTxtID.getText()));
                objusuario.setNOME(jTxtNome.getText());
                objusuario.setCADASTRO(jTxtCadastro.getText());
                objusuario.setATIVO((jCheckAtivo.isSelected() ? 1 : 0));
                UsuarioController usuariocontroller = new UsuarioController();
                usuariocontroller.gravar(getOperacao(), objusuario);

                JOptionPane.showMessageDialog(null, "Dados Gravados com Sucesso");
                consultaUsuario();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro na Gravação do Usuário \n" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jBttnGravarActionPerformed

    private void jBttnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnConsultaActionPerformed
        consultaUsuario();

    }//GEN-LAST:event_jBttnConsultaActionPerformed

    private void jBttnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnLimparActionPerformed
        jTxtConsultaID1.setText("");
        jTxtConsultaID2.setText("");
        jTxtConsultaNome.setText("");
    }//GEN-LAST:event_jBttnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnAlterar;
    private javax.swing.JButton jBttnConsulta;
    private javax.swing.JButton jBttnExcluir;
    private javax.swing.JButton jBttnGravar;
    private javax.swing.JButton jBttnLimpar;
    private javax.swing.JButton jBttnNovo;
    private javax.swing.JButton jBttnSair;
    private javax.swing.JCheckBox jCheckAtivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableConsulta;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField jTxtCadastro;
    private javax.swing.JTextField jTxtConsultaID1;
    private javax.swing.JTextField jTxtConsultaID2;
    private javax.swing.JTextField jTxtConsultaNome;
    private javax.swing.JTextField jTxtID;
    private javax.swing.JTextField jTxtNome;
    // End of variables declaration//GEN-END:variables
}
