/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula06;

import javax.swing.JOptionPane;

/**
 *
 * @author guilherme
 */
public class Principal extends javax.swing.JFrame {

    private CrudJDBC crudJDBC;
    private String operacao = "consulta";

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        configurarBanco();
        crudJDBC = new CrudJDBC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar = new javax.swing.JToolBar();
        jBttnIncluir = new javax.swing.JButton();
        jBttnAlterar = new javax.swing.JButton();
        jBttnConsultar = new javax.swing.JButton();
        jBttnExcluir = new javax.swing.JButton();
        jBttnSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLblSGBD = new javax.swing.JLabel();
        jLblBanco = new javax.swing.JLabel();
        jLblUsuario = new javax.swing.JLabel();
        jLblSQL = new javax.swing.JLabel();
        jComboSGBD = new javax.swing.JComboBox<>();
        jTxtBanco = new javax.swing.JTextField();
        jTxtUsuario = new javax.swing.JTextField();
        jLblDriver = new javax.swing.JLabel();
        jLblSenha = new javax.swing.JLabel();
        jPasswd = new javax.swing.JPasswordField();
        jTxtDriver = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAreaSQL = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLblResultado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar.setRollover(true);

        jBttnIncluir.setText("Incluir");
        jBttnIncluir.setFocusable(false);
        jBttnIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBttnIncluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBttnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnIncluirActionPerformed(evt);
            }
        });
        jToolBar.add(jBttnIncluir);

        jBttnAlterar.setText("Alterar");
        jBttnAlterar.setFocusable(false);
        jBttnAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBttnAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBttnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnAlterarActionPerformed(evt);
            }
        });
        jToolBar.add(jBttnAlterar);

        jBttnConsultar.setText("Consultar");
        jBttnConsultar.setFocusable(false);
        jBttnConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBttnConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBttnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnConsultarActionPerformed(evt);
            }
        });
        jToolBar.add(jBttnConsultar);

        jBttnExcluir.setText("Excluir");
        jBttnExcluir.setFocusable(false);
        jBttnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBttnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBttnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnExcluirActionPerformed(evt);
            }
        });
        jToolBar.add(jBttnExcluir);

        jBttnSair.setText("Sair");
        jBttnSair.setFocusable(false);
        jBttnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBttnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBttnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnSairActionPerformed(evt);
            }
        });
        jToolBar.add(jBttnSair);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informaçoes de Conexao"));

        jLblSGBD.setText("SGBD");

        jLblBanco.setText("Banco");

        jLblUsuario.setText("Usuario");

        jLblSQL.setText("SQL");

        jComboSGBD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oracle", "PostgreeSQL", "MySQL"}));

        jLblDriver.setText("Driver");

        jLblSenha.setText("Senha");

        jAreaSQL.setColumns(20);
        jAreaSQL.setRows(5);
        jScrollPane1.setViewportView(jAreaSQL);

        jButton1.setText("Executar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLblResultado.setText("Resultado");

        jTxtResultado.setColumns(20);
        jTxtResultado.setRows(5);
        jScrollPane2.setViewportView(jTxtResultado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLblUsuario)
                                .addComponent(jLblSGBD, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLblBanco, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLblSQL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtBanco)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboSGBD, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(jLblDriver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLblSenha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLblResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblSGBD)
                    .addComponent(jComboSGBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblDriver)
                    .addComponent(jTxtDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblBanco)
                    .addComponent(jTxtBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblUsuario)
                    .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblSenha)
                    .addComponent(jPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLblSQL)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLblResultado)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarBanco() {
        switch (jComboSGBD.getSelectedItem().toString()) {
            case "PostgreSQL":
                jTxtDriver.setText("org.postgresql.Driver");
                jTxtBanco.setText("jdbc:postgresql://localhost/teste");
                jTxtUsuario.setText("teste");
                jPasswd.setText("teste");
                break;
            case "Oracle":
                jTxtDriver.setText("oracle.jdbc.OracleDriver");
                jTxtBanco.setText("jdbc:oracle:thin:@10.10.10.66:1521/pdb02");
                jTxtUsuario.setText("guilherme");
                jPasswd.setText("123");
                break;
            case "MySQL":
                jTxtDriver.setText("com.mysql.jdbc.Driver");
                jTxtBanco.setText("jdbc:mysql://localhost:3306/test");
                jTxtUsuario.setText("root");
                jPasswd.setText("root");
                break;
            default:
                JOptionPane.showMessageDialog(null,
                        "Banco de dados não possui driver JDBC instalado\n"
                        + "Confira no arquivo pom.xml");

        }
    }
    private void jBttnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnAlterarActionPerformed
        jAreaSQL.setText("UPDATE FILMES SET GENERO = 'AVENTURA' WHERE ID = 1");
        operacao = "alterar";
    }//GEN-LAST:event_jBttnAlterarActionPerformed

    private void jBttnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnExcluirActionPerformed
        jAreaSQL.setText("DELETE FROM FILMES WHERE ID = 1");
        operacao = "excluir";
    }//GEN-LAST:event_jBttnExcluirActionPerformed

    private void jBttnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnSairActionPerformed
        System.exit(0);

    }//GEN-LAST:event_jBttnSairActionPerformed

    private void jBttnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnConsultarActionPerformed
        jAreaSQL.setText("SELECT * FROM FILMES");
        operacao = "consultar";
    }//GEN-LAST:event_jBttnConsultarActionPerformed

    private void jBttnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnIncluirActionPerformed
        jAreaSQL.setText("INSERT INTO FILMES(ID, NOME, DATA_LANCAMENTO, GENERO, CLASSIFICACAO) VALUES (1, 'VINGADORES', TO_DATE('10/09/2019'), 'AÇAO', '16 ANOS')");
        operacao = "incluir";
    }//GEN-LAST:event_jBttnIncluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String driver = jTxtDriver.getText();
        String banco = jTxtBanco.getText();
        String usuario = jTxtUsuario.getText();
        String senha = jPasswd.getText();
        String sql = jAreaSQL.getText();

        crudJDBC.conectar(driver, banco, usuario, senha);

        switch (operacao) {
            case "consultar":
                jTxtResultado.setText(crudJDBC.consultar(sql));
                break;
            case "incluir":
                crudJDBC.incluir(sql);
                break;
            case "alterar":
                crudJDBC.alterar(sql);
                break;
            case "excluir":
                crudJDBC.excluir(sql);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Operação Inválida: " + operacao);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jAreaSQL;
    private javax.swing.JButton jBttnAlterar;
    private javax.swing.JButton jBttnConsultar;
    private javax.swing.JButton jBttnExcluir;
    private javax.swing.JButton jBttnIncluir;
    private javax.swing.JButton jBttnSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboSGBD;
    private javax.swing.JLabel jLblBanco;
    private javax.swing.JLabel jLblDriver;
    private javax.swing.JLabel jLblResultado;
    private javax.swing.JLabel jLblSGBD;
    private javax.swing.JLabel jLblSQL;
    private javax.swing.JLabel jLblSenha;
    private javax.swing.JLabel jLblUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar;
    private javax.swing.JTextField jTxtBanco;
    private javax.swing.JTextField jTxtDriver;
    private javax.swing.JTextArea jTxtResultado;
    private javax.swing.JTextField jTxtUsuario;
    // End of variables declaration//GEN-END:variables
}
