package view;

import controller.EnderecoController;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import model.EnderecoModel;

/**
 *
 * @author guilherme
 */
public class ViewEnderecos extends javax.swing.JFrame {

    private String operacao;
    private String colunas[] = {"ID", "TIPO", "LOGRADOURO", "CEP", "NUMERO", "CIDADE", "ESTADO"};
    // esse objeto será vinculado com a tabela
    // selecione o objeto tabela, clique em PROPRIEDADES e encontre MODEL
    // no combo "Definir Propriedades" escolha "Código Personalizado"
    // digite o objeto DefaultTableModel, neste exemplo é tabela(criado logo abaixo)
    private ArrayList<EnderecoModel> lista;
    private EnderecoTableModel tabela;

    private String getOperacao() {
        return operacao;
    }

    public ViewEnderecos() {
        initComponents();
        setLocationRelativeTo(null);
        consultar();
        // adiciona evento para qdo navegar no JTable, atualizar os dados nos JTextField´s
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent evt) {
                if (evt.getValueIsAdjusting()) {
                    return;
                }
                int selecionado = jTable1.getSelectedRow();
                if (selecionado >= 0) {
                    mostrar(lista.get(selecionado));
                }
            }
        });
    }

    private void mostrar(EnderecoModel endereco) {
        jTxtID_END.setText(String.valueOf(endereco.getID_ENDERECO()));
        jComboTIPO.setSelectedItem(endereco.getTIPO());
        jTxtLOGRADOURO.setText(endereco.getLOGRADOURO());
        jTxtCEP.setText(endereco.getCEP());
        jTxtNUMERO.setText(String.valueOf(endereco.getNUMERO()));
        jTxtCIDADE.setText(endereco.getCIDADE());
        jComboESTADO.setSelectedItem(endereco.getESTADO());
    }

    private void consultar() {
        try {
            String condicao = filtroConsulta();
            EnderecoController usuariocontroller = new EnderecoController();
            lista = null;
            lista = usuariocontroller.consultar(condicao);
            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Não Existem Usuários Cadastrados !");
            } else {
                tabela = new EnderecoTableModel(lista, colunas);
                jTable1.setModel(tabela);
                jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na Consulta do Usuário \n" + ex.getMessage());
        }
    }

    private String filtroConsulta() {
        String condicao = "";
        if (!jTxtID_END.getText().trim().equals("")) {
            condicao += "(ID_ENDERECO >= " + jTxtID_END.getText() + ")";
        }
        if (!jComboTIPO.getSelectedItem().equals("")) {
            if (!condicao.isEmpty()) {
                condicao += " AND ";
            }
            condicao += "(ID_ENDERECO <= " + jComboTIPO.getSelectedItem() + ")";
        }
        if (!jTxtLOGRADOURO.getText().trim().equals("")) {
            if (!condicao.isEmpty()) {
                condicao += " AND ";
            }
            if (!jTxtCEP.getText().trim().equals("")) {
                if (!condicao.isEmpty()) {
                    condicao += " AND ";
                }
                if (!jTxtNUMERO.getText().trim().equals("")) {
                    if (!condicao.isEmpty()) {
                        condicao += " AND ";
                    }
                    if (!jTxtCIDADE.getText().trim().equals("")) {
                        if (!condicao.isEmpty()) {
                            condicao += " AND ";
                        }
                        if (!jComboESTADO.getSelectedItem().equals("")) {
                            if (!condicao.isEmpty()) {
                                condicao += " AND ";
                            }
                            condicao += "( upper(LOGRADOURO) LIKE ('%" + jTxtLOGRADOURO.getText().toUpperCase() + "%'))";
                        }
                    }
                }
            }
        }
        return condicao;
    }

    ;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtID_END = new javax.swing.JTextField();
        jTxtLOGRADOURO = new javax.swing.JTextField();
        jTxtCEP = new javax.swing.JTextField();
        jTxtNUMERO = new javax.swing.JTextField();
        jTxtCIDADE = new javax.swing.JTextField();
        jComboTIPO = new javax.swing.JComboBox<>();
        jComboESTADO = new javax.swing.JComboBox<>();
        jBttnCadastrar = new javax.swing.JButton();
        jBttnConsultar = new javax.swing.JButton();
        jBttnAlterar = new javax.swing.JButton();
        jBttnExcluir = new javax.swing.JButton();
        jTableConsulta = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Endereços"));

        jLabel1.setText("ID_ENDERECO");

        jLabel2.setText("TIPO");

        jLabel3.setText("LOGRADOURO");

        jLabel4.setText("CEP");

        jLabel5.setText("NUMERO");

        jLabel6.setText("CIDADE");

        jLabel7.setText("ESTADO");

        jTxtID_END.setEditable(false);

        jComboTIPO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RUA", "AVENIDA", "TRAVESSA", "ALAMEDA" }));

        jComboESTADO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"  }));

        jBttnCadastrar.setText("CADASTRAR");
        jBttnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnCadastrarActionPerformed(evt);
            }
        });

        jBttnConsultar.setText("CONSULTAR");

        jBttnAlterar.setText("ALTERAR");

        jBttnExcluir.setText("EXCLUIR");
        jBttnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtID_END, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboTIPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtLOGRADOURO))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboESTADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBttnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBttnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBttnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBttnCadastrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNUMERO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCIDADE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtID_END, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboTIPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtLOGRADOURO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtNUMERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtCIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboESTADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBttnCadastrar)
                    .addComponent(jBttnConsultar)
                    .addComponent(jBttnAlterar)
                    .addComponent(jBttnExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableConsulta.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTableConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTableConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnCadastrarActionPerformed

        if (JOptionPane.showConfirmDialog(null, "Confirma Gravação deste Endereço ?",
                "Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                EnderecoModel objeto = new EnderecoModel();
                objeto.setID_ENDERECO(Integer.parseInt(jTxtID_END.getText()));
                objeto.setTIPO(jComboTIPO.getSelectedItem().toString());
                objeto.setLOGRADOURO(jTxtLOGRADOURO.getText());
                objeto.setCEP(jTxtCEP.getText());
                objeto.setNUMERO(Integer.parseInt(jTxtNUMERO.getText()));
                objeto.setCIDADE(jTxtCIDADE.getText());
                objeto.setESTADO(jComboESTADO.getSelectedItem().toString());
                EnderecoController controller = new EnderecoController();
                controller.gravar(getOperacao(), objeto);

                JOptionPane.showMessageDialog(null, "Dados Gravados com Sucesso");
                consultar();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro na Gravação \n" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jBttnCadastrarActionPerformed

    private void jBttnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnExcluirActionPerformed

        if (JOptionPane.showConfirmDialog(null, "Confirma Exclusão deste Registro ?",
                "Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                EnderecoModel objeto = new EnderecoModel();
                objeto.setID_ENDERECO(Integer.parseInt(jTxtID_END.getText()));
                objeto.setTIPO(jComboTIPO.getSelectedItem().toString());
                objeto.setLOGRADOURO(jTxtLOGRADOURO.getText());
                objeto.setCEP(jTxtCEP.getText());
                objeto.setNUMERO(Integer.parseInt(jTxtNUMERO.getText()));
                objeto.setCIDADE(jTxtCIDADE.getText());
                objeto.setESTADO(jComboESTADO.getSelectedItem().toString());

                EnderecoController controller = new EnderecoController();
                controller.excluir(objeto);

                JOptionPane.showMessageDialog(null, "Registro Excluído com Sucesso");
                consultar();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro na Exclusão de Registro \n" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jBttnExcluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnAlterar;
    private javax.swing.JButton jBttnCadastrar;
    private javax.swing.JButton jBttnConsultar;
    private javax.swing.JButton jBttnExcluir;
    private javax.swing.JComboBox<String> jComboESTADO;
    private javax.swing.JComboBox<String> jComboTIPO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane jTableConsulta;
    private javax.swing.JTextField jTxtCEP;
    private javax.swing.JTextField jTxtCIDADE;
    private javax.swing.JTextField jTxtID_END;
    private javax.swing.JTextField jTxtLOGRADOURO;
    private javax.swing.JTextField jTxtNUMERO;
    // End of variables declaration//GEN-END:variables

}
